/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package uis;

import java.awt.Cursor;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JComponent;
import main.SVGImage;

/**
 *
 * @author gamitha
 */
public class Add extends javax.swing.JPanel {

    /**
     * Creates new form Add
     */
    public Add() {
        initComponents();
        
        // Visible off
        addTasks.setVisible(false);
        addInventory.setVisible(false);
        addTransactions.setVisible(false);
        addEmployees.setVisible(false);
        
        
        // Set SVGs
        sVGAddSegCtrlBg.setSvgImage("./svgcomponents/AddSegCtrlBg.svg", 448, 22);
        sVGAddSegCtrlFieldMetrics.setSvgImage("./svgcomponents/AddSegCtrlFieldMetricsSelected.svg", 90, 20);
        sVGAddSegCtrlTasks.setSvgImage("./svgcomponents/AddSegCtrlTasks.svg", 90, 20);
        sVGAddSegCtrlInventory.setSvgImage("./svgcomponents/AddSegCtrlInventory.svg", 90, 20);
        sVGAddSegCtrlTransactions.setSvgImage("./svgcomponents/AddSegCtrlTransactions.svg", 90, 20);
        sVGAddSegCtrlEmployees.setSvgImage("./svgcomponents/AddSegCtrlEmployees.svg", 90, 20);
        
        // Set hand cursors
        Cursor hand = new Cursor(Cursor.HAND_CURSOR); // Change to desired cursor type
        sVGAddSegCtrlTasks.setCursor(hand);
        sVGAddSegCtrlInventory.setCursor(hand);
        sVGAddSegCtrlTransactions.setCursor(hand);
        sVGAddSegCtrlEmployees.setCursor(hand);
    }
    
    private void selectSegCtrlButton(String button) {
        // Declare and initialize the map
        Map<String, SVGImage> svgMap = new HashMap<>();
        svgMap.put("AddSegCtrlFieldMetrics", sVGAddSegCtrlFieldMetrics);
        svgMap.put("AddSegCtrlTasks", sVGAddSegCtrlTasks);
        svgMap.put("AddSegCtrlInventory", sVGAddSegCtrlInventory);
        svgMap.put("AddSegCtrlTransactions", sVGAddSegCtrlTransactions);
        svgMap.put("AddSegCtrlEmployees", sVGAddSegCtrlEmployees);
        
        // Declare and initialize an array of Sidebar buttons
        String[] segCtrlButtons = {"AddSegCtrlFieldMetrics", "AddSegCtrlTasks", "AddSegCtrlInventory", "AddSegCtrlTransactions", "AddSegCtrlEmployees"};
        
        // Intialize cursor objects
        Cursor hand = new Cursor(Cursor.HAND_CURSOR);
        Cursor defaultCursor = new Cursor(Cursor.DEFAULT_CURSOR);
        
        // Iterate thorugh the array
        for (String idx : segCtrlButtons) {
            SVGImage svg = svgMap.get(idx); // Create the svg name from the String of the index
            if (idx.equals(button)) {
                // Select button
                svg.setSvgImage("./svgcomponents/" + idx + "Selected.svg", 90, 20);
                svg.setCursor(defaultCursor);
            } else {
                // Unselect other buttons
                svg.setSvgImage("./svgcomponents/" + idx + ".svg", 90, 20);
                svg.setCursor(hand);
            }
        }
        
        // Repaint
        this.revalidate(); // TODO: check if this correct
        this.repaint();
    }
    
    private void selectForm(String selectedForm) {
        // Declare and initialize the map
        Map<String, JComponent> formMap = new HashMap<>();
        formMap.put("AddSegCtrlFieldMetrics", addFieldMetrics);
        formMap.put("AddSegCtrlTasks", addTasks);
        formMap.put("AddSegCtrlInventory", addInventory);
        formMap.put("AddSegCtrlTransactions", addTransactions);
        formMap.put("AddSegCtrlEmployees", addEmployees);

        // Iterate through the map
        for (Map.Entry<String, JComponent> entry : formMap.entrySet()) {
            JComponent component = entry.getValue();
            if (entry.getKey().equals(selectedForm)) {
                // Select Content Area
                component.setVisible(true);
            } else {
                // Unselect other JPanels
                component.setVisible(false);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sVGAddSegCtrlFieldMetrics = new main.SVGImage();
        sVGAddSegCtrlTasks = new main.SVGImage();
        sVGAddSegCtrlInventory = new main.SVGImage();
        sVGAddSegCtrlTransactions = new main.SVGImage();
        sVGAddSegCtrlEmployees = new main.SVGImage();
        sVGAddSegCtrlBg = new main.SVGImage();
        addEmployees = new uis.AddEmployees();
        addTransactions = new uis.AddTransactions();
        addTasks = new uis.AddTasks();
        addFieldMetrics = new uis.AddFieldMetrics();
        addInventory = new uis.AddInventory();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(null);
        setSize(new java.awt.Dimension(649, 478));
        setLayout(null);

        sVGAddSegCtrlFieldMetrics.setForeground(new java.awt.Color(0, 0, 0));
        sVGAddSegCtrlFieldMetrics.setText("sVGAddSegCtrlFieldMetrics");
        sVGAddSegCtrlFieldMetrics.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sVGAddSegCtrlFieldMetricsMouseClicked(evt);
            }
        });
        add(sVGAddSegCtrlFieldMetrics);
        sVGAddSegCtrlFieldMetrics.setBounds(21, 21, 90, 20);

        sVGAddSegCtrlTasks.setForeground(new java.awt.Color(0, 0, 0));
        sVGAddSegCtrlTasks.setText("sVGAddSegCtrlTasks");
        sVGAddSegCtrlTasks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sVGAddSegCtrlTasksMouseClicked(evt);
            }
        });
        add(sVGAddSegCtrlTasks);
        sVGAddSegCtrlTasks.setBounds(110, 20, 90, 20);

        sVGAddSegCtrlInventory.setForeground(new java.awt.Color(0, 0, 0));
        sVGAddSegCtrlInventory.setText("sVGAddSegCtrlInventory");
        sVGAddSegCtrlInventory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sVGAddSegCtrlInventoryMouseClicked(evt);
            }
        });
        add(sVGAddSegCtrlInventory);
        sVGAddSegCtrlInventory.setBounds(199, 21, 90, 20);

        sVGAddSegCtrlTransactions.setForeground(new java.awt.Color(0, 0, 0));
        sVGAddSegCtrlTransactions.setText("sVGAddSegCtrlTransactions");
        sVGAddSegCtrlTransactions.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sVGAddSegCtrlTransactionsMouseClicked(evt);
            }
        });
        add(sVGAddSegCtrlTransactions);
        sVGAddSegCtrlTransactions.setBounds(288, 21, 90, 20);

        sVGAddSegCtrlEmployees.setForeground(new java.awt.Color(0, 0, 0));
        sVGAddSegCtrlEmployees.setText("sVGAddSegCtrlEmployees");
        sVGAddSegCtrlEmployees.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sVGAddSegCtrlEmployeesMouseClicked(evt);
            }
        });
        add(sVGAddSegCtrlEmployees);
        sVGAddSegCtrlEmployees.setBounds(377, 21, 90, 20);

        sVGAddSegCtrlBg.setForeground(new java.awt.Color(0, 0, 0));
        sVGAddSegCtrlBg.setText("sVGAddSegCtrlBg");
        add(sVGAddSegCtrlBg);
        sVGAddSegCtrlBg.setBounds(20, 20, 448, 22);
        add(addEmployees);
        addEmployees.setBounds(0, 52, 649, 426);
        add(addTransactions);
        addTransactions.setBounds(0, 52, 649, 426);
        add(addTasks);
        addTasks.setBounds(0, 52, 649, 426);

        javax.swing.GroupLayout addFieldMetricsLayout = new javax.swing.GroupLayout(addFieldMetrics);
        addFieldMetrics.setLayout(addFieldMetricsLayout);
        addFieldMetricsLayout.setHorizontalGroup(
            addFieldMetricsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 649, Short.MAX_VALUE)
        );
        addFieldMetricsLayout.setVerticalGroup(
            addFieldMetricsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 426, Short.MAX_VALUE)
        );

        add(addFieldMetrics);
        addFieldMetrics.setBounds(0, 52, 649, 426);
        add(addInventory);
        addInventory.setBounds(0, 52, 649, 426);
    }// </editor-fold>//GEN-END:initComponents

    private void sVGAddSegCtrlFieldMetricsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sVGAddSegCtrlFieldMetricsMouseClicked
        // Select Form
        selectForm("AddSegCtrlFieldMetrics");

        // Select Button
        selectSegCtrlButton("AddSegCtrlFieldMetrics");
    }//GEN-LAST:event_sVGAddSegCtrlFieldMetricsMouseClicked

    private void sVGAddSegCtrlTasksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sVGAddSegCtrlTasksMouseClicked
        // Select Form
        selectForm("AddSegCtrlTasks");

        // Select Button
        selectSegCtrlButton("AddSegCtrlTasks");
    }//GEN-LAST:event_sVGAddSegCtrlTasksMouseClicked

    private void sVGAddSegCtrlInventoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sVGAddSegCtrlInventoryMouseClicked
        // Select Form
        selectForm("AddSegCtrlInventory");

        // Select Button
        selectSegCtrlButton("AddSegCtrlInventory");
    }//GEN-LAST:event_sVGAddSegCtrlInventoryMouseClicked

    private void sVGAddSegCtrlTransactionsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sVGAddSegCtrlTransactionsMouseClicked
        // Select Form
        selectForm("AddSegCtrlTransactions");

        // Select Button
        selectSegCtrlButton("AddSegCtrlTransactions");
    }//GEN-LAST:event_sVGAddSegCtrlTransactionsMouseClicked

    private void sVGAddSegCtrlEmployeesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sVGAddSegCtrlEmployeesMouseClicked
        // Select Form
        selectForm("AddSegCtrlEmployees");

        // Select Button
        selectSegCtrlButton("AddSegCtrlEmployees");
    }//GEN-LAST:event_sVGAddSegCtrlEmployeesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private uis.AddEmployees addEmployees;
    private uis.AddFieldMetrics addFieldMetrics;
    private uis.AddInventory addInventory;
    private uis.AddTasks addTasks;
    private uis.AddTransactions addTransactions;
    private main.SVGImage sVGAddSegCtrlBg;
    private main.SVGImage sVGAddSegCtrlEmployees;
    private main.SVGImage sVGAddSegCtrlFieldMetrics;
    private main.SVGImage sVGAddSegCtrlInventory;
    private main.SVGImage sVGAddSegCtrlTasks;
    private main.SVGImage sVGAddSegCtrlTransactions;
    // End of variables declaration//GEN-END:variables
}
