/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

package uis;

/**
 *
 * @author gamitha
 */
public class AddEmployees extends javax.swing.JPanel {

    /** Creates new form AddEmployees */
    public AddEmployees() {
        initComponents();
        
        sVGAddBtn.setSvgImage("./svgcomponents/AddBtn.svg", 39, 22);
        sVGAddEmployeesForm.setSvgImage("./svgcomponents/AddEmployeesForm.svg", 451, 221);
        sVGAddEmployeesFName.setSvgImage("./svgcomponents/AddEmployeesFName.svg", 431, 37);
        sVGAddEmployeesLName.setSvgImage("./svgcomponents/AddEmployeesLName.svg", 431, 37);
        sVGAddEmployeesRole.setSvgImage("./svgcomponents/AddEmployeesRole.svg", 431, 36);
        sVGAddEmployeesPhone.setSvgImage("./svgcomponents/AddEmployeesPhone.svg", 431, 37);
        sVGAddEmployeesEmail.setSvgImage("./svgcomponents/AddEmployeesEmail.svg", 431, 37);
        sVGAddEmployeesAddress.setSvgImage("./svgcomponents/AddEmployeesAddress.svg", 431, 37);
        sVGAddEmployeesFNameTextBox.setSvgImage("./svgcomponents/AddEmployeesFNameTextBox.svg", 160, 23);
        sVGAddEmployeesLNameTextBox.setSvgImage("./svgcomponents/AddEmployeesLNameTextBox.svg", 160, 23);
        sVGAddEmployeesRoleComboBox.setSvgImage("./svgcomponents/AddEmployeesRoleComboBox.svg", 160, 21);
        sVGAddEmployeesPhoneTextBox.setSvgImage("./svgcomponents/AddEmployeesPhoneTextBox.svg", 160, 23);
        sVGAddEmployeesEmailTextBox.setSvgImage("./svgcomponents/AddEmployeesEmailTextBox.svg", 160, 23);
        sVGAddEmployeesAddressTextBox.setSvgImage("./svgcomponents/AddEmployeesAddressTextBox.svg", 160, 23);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sVGAddBtn = new main.SVGImage();
        sVGAddEmployeesFNameTextBox = new main.SVGImage();
        sVGAddEmployeesLNameTextBox = new main.SVGImage();
        sVGAddEmployeesPhoneTextBox = new main.SVGImage();
        sVGAddEmployeesEmailTextBox = new main.SVGImage();
        sVGAddEmployeesAddressTextBox = new main.SVGImage();
        sVGAddEmployeesRoleComboBox = new main.SVGImage();
        sVGAddEmployeesFName = new main.SVGImage();
        sVGAddEmployeesLName = new main.SVGImage();
        sVGAddEmployeesRole = new main.SVGImage();
        sVGAddEmployeesPhone = new main.SVGImage();
        sVGAddEmployeesEmail = new main.SVGImage();
        sVGAddEmployeesAddress = new main.SVGImage();
        sVGAddEmployeesForm = new main.SVGImage();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(null);
        setPreferredSize(new java.awt.Dimension(649, 426));
        setSize(new java.awt.Dimension(649, 426));
        setLayout(null);

        sVGAddBtn.setForeground(new java.awt.Color(0, 0, 0));
        sVGAddBtn.setText("sVGAddButton");
        add(sVGAddBtn);
        sVGAddBtn.setBounds(432, 244, 39, 22);

        sVGAddEmployeesFNameTextBox.setForeground(new java.awt.Color(0, 0, 0));
        sVGAddEmployeesFNameTextBox.setText("sVGAddEmployeesFNameTextBox");
        add(sVGAddEmployeesFNameTextBox);
        sVGAddEmployeesFNameTextBox.setBounds(301, 17, 160, 23);

        sVGAddEmployeesLNameTextBox.setForeground(new java.awt.Color(0, 0, 0));
        sVGAddEmployeesLNameTextBox.setText("sVGAddEmployeesLNameTextBox");
        add(sVGAddEmployeesLNameTextBox);
        sVGAddEmployeesLNameTextBox.setBounds(301, 54, 160, 23);

        sVGAddEmployeesPhoneTextBox.setForeground(new java.awt.Color(0, 0, 0));
        sVGAddEmployeesPhoneTextBox.setText("sVGAddEmployeesPhoneTextBox");
        add(sVGAddEmployeesPhoneTextBox);
        sVGAddEmployeesPhoneTextBox.setBounds(301, 127, 160, 23);

        sVGAddEmployeesEmailTextBox.setForeground(new java.awt.Color(0, 0, 0));
        sVGAddEmployeesEmailTextBox.setText("sVGAddEmployeesEmailTextBox");
        add(sVGAddEmployeesEmailTextBox);
        sVGAddEmployeesEmailTextBox.setBounds(301, 164, 160, 23);

        sVGAddEmployeesAddressTextBox.setForeground(new java.awt.Color(0, 0, 0));
        sVGAddEmployeesAddressTextBox.setText("sVGAddEmployeesAddressTextBox");
        add(sVGAddEmployeesAddressTextBox);
        sVGAddEmployeesAddressTextBox.setBounds(301, 201, 160, 23);

        sVGAddEmployeesRoleComboBox.setForeground(new java.awt.Color(0, 0, 0));
        sVGAddEmployeesRoleComboBox.setText("sVGAddEmployeesRoleComboBox");
        add(sVGAddEmployeesRoleComboBox);
        sVGAddEmployeesRoleComboBox.setBounds(301, 92, 160, 21);

        sVGAddEmployeesFName.setForeground(new java.awt.Color(0, 0, 0));
        sVGAddEmployeesFName.setText("sVGAddEmployeesFName");
        add(sVGAddEmployeesFName);
        sVGAddEmployeesFName.setBounds(30, 10, 431, 37);

        sVGAddEmployeesLName.setForeground(new java.awt.Color(0, 0, 0));
        sVGAddEmployeesLName.setText("sVGAddEmployeesLName");
        add(sVGAddEmployeesLName);
        sVGAddEmployeesLName.setBounds(30, 47, 431, 37);

        sVGAddEmployeesRole.setForeground(new java.awt.Color(0, 0, 0));
        sVGAddEmployeesRole.setText("sVGAddEmployeesRole");
        add(sVGAddEmployeesRole);
        sVGAddEmployeesRole.setBounds(30, 84, 431, 36);

        sVGAddEmployeesPhone.setForeground(new java.awt.Color(0, 0, 0));
        sVGAddEmployeesPhone.setText("sVGAddEmployeesPhone");
        add(sVGAddEmployeesPhone);
        sVGAddEmployeesPhone.setBounds(30, 120, 431, 37);

        sVGAddEmployeesEmail.setForeground(new java.awt.Color(0, 0, 0));
        sVGAddEmployeesEmail.setText("sVGAddEmployeesEmail");
        add(sVGAddEmployeesEmail);
        sVGAddEmployeesEmail.setBounds(30, 157, 431, 37);

        sVGAddEmployeesAddress.setForeground(new java.awt.Color(0, 0, 0));
        sVGAddEmployeesAddress.setText("sVGAddEmployeesAddress");
        add(sVGAddEmployeesAddress);
        sVGAddEmployeesAddress.setBounds(30, 194, 431, 37);

        sVGAddEmployeesForm.setForeground(new java.awt.Color(0, 0, 0));
        sVGAddEmployeesForm.setText("sVGAddEmployeesForm");
        add(sVGAddEmployeesForm);
        sVGAddEmployeesForm.setBounds(20, 10, 451, 221);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private main.SVGImage sVGAddBtn;
    private main.SVGImage sVGAddEmployeesAddress;
    private main.SVGImage sVGAddEmployeesAddressTextBox;
    private main.SVGImage sVGAddEmployeesEmail;
    private main.SVGImage sVGAddEmployeesEmailTextBox;
    private main.SVGImage sVGAddEmployeesFName;
    private main.SVGImage sVGAddEmployeesFNameTextBox;
    private main.SVGImage sVGAddEmployeesForm;
    private main.SVGImage sVGAddEmployeesLName;
    private main.SVGImage sVGAddEmployeesLNameTextBox;
    private main.SVGImage sVGAddEmployeesPhone;
    private main.SVGImage sVGAddEmployeesPhoneTextBox;
    private main.SVGImage sVGAddEmployeesRole;
    private main.SVGImage sVGAddEmployeesRoleComboBox;
    // End of variables declaration//GEN-END:variables

}
