/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

package uis;

import java.awt.Cursor;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import java.sql.*;

/**
 *
 * @author gamitha
 */
public class AddEmployees extends javax.swing.JPanel {

    private void addFocusListener(JTextField textField) {
        textField.addFocusListener(new FocusAdapter() {
            @Override
            public void focusLost(FocusEvent e) {
                if (textField.getText().trim().isEmpty()) {
                    textField.setVisible(false);
                }
            }
        });
    }
    
    /** Creates new form AddEmployees */
    public AddEmployees() {
        initComponents();
        
        // Set visibility off
        txtFName.setVisible(false);
        txtLName.setVisible(false);
        txtPhone.setVisible(false);
        txtEmail.setVisible(false);
        txtAddress.setVisible(false);
        txtPassword.setVisible(false);
        cmbRole.setVisible(false);
        
        // Add focus listeners to textboxes
        addFocusListener(txtFName);
        addFocusListener(txtLName);
        addFocusListener(txtPhone);
        addFocusListener(txtEmail);
        addFocusListener(txtAddress);
        addFocusListener(txtPassword);
        
        // Set SVGs
        sVGAddBtn.setSvgImage("./svgcomponents/AddBtn.svg", 39, 22);
        sVGAddEmployeesForm.setSvgImage("./svgcomponents/AddEmployeesForm.svg", 451, 258);
        sVGAddEmployeesFName.setSvgImage("./svgcomponents/AddEmployeesFName.svg", 431, 37);
        sVGAddEmployeesLName.setSvgImage("./svgcomponents/AddEmployeesLName.svg", 431, 37);
        sVGAddEmployeesRole.setSvgImage("./svgcomponents/AddEmployeesRole.svg", 431, 36);
        sVGAddEmployeesPhone.setSvgImage("./svgcomponents/AddEmployeesPhone.svg", 431, 37);
        sVGAddEmployeesEmail.setSvgImage("./svgcomponents/AddEmployeesEmail.svg", 431, 37);
        sVGAddEmployeesAddress.setSvgImage("./svgcomponents/AddEmployeesAddress.svg", 431, 37);
        sVGAddEmployeesPassword.setSvgImage("./svgcomponents/AddEmployeesPassword.svg", 431, 37);
        sVGAddEmployeesFNameTextBox.setSvgImage("./svgcomponents/AddEmployeesFNameTextBox.svg", 160, 23);
        sVGAddEmployeesLNameTextBox.setSvgImage("./svgcomponents/AddEmployeesLNameTextBox.svg", 160, 23);
        sVGAddEmployeesRoleComboBox.setSvgImage("./svgcomponents/AddEmployeesRoleComboBox.svg", 160, 21);
        sVGAddEmployeesPhoneTextBox.setSvgImage("./svgcomponents/AddEmployeesPhoneTextBox.svg", 160, 23);
        sVGAddEmployeesEmailTextBox.setSvgImage("./svgcomponents/AddEmployeesEmailTextBox.svg", 160, 23);
        sVGAddEmployeesAddressTextBox.setSvgImage("./svgcomponents/AddEmployeesAddressTextBox.svg", 160, 23);
        sVGAddEmployeesPasswordTextBox.setSvgImage("./svgcomponents/AddEmployeesPasswordTextBox.svg", 160, 23);
        
        // Set Cursors
        Cursor txtCur = new Cursor(Cursor.TEXT_CURSOR);
        Cursor hand = new Cursor(Cursor.HAND_CURSOR);
        sVGAddEmployeesFNameTextBox.setCursor(txtCur);
        sVGAddEmployeesLNameTextBox.setCursor(txtCur);
        sVGAddEmployeesPhoneTextBox.setCursor(txtCur);
        sVGAddEmployeesEmailTextBox.setCursor(txtCur);
        sVGAddEmployeesAddressTextBox.setCursor(txtCur);
        sVGAddEmployeesPasswordTextBox.setCursor(txtCur);
        sVGAddBtn.setCursor(hand);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtFName = new javax.swing.JTextField();
        txtLName = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        cmbRole = new javax.swing.JComboBox<>();
        sVGAddBtn = new main.SVGImage();
        sVGAddEmployeesFNameTextBox = new main.SVGImage();
        sVGAddEmployeesLNameTextBox = new main.SVGImage();
        sVGAddEmployeesPhoneTextBox = new main.SVGImage();
        sVGAddEmployeesEmailTextBox = new main.SVGImage();
        sVGAddEmployeesAddressTextBox = new main.SVGImage();
        sVGAddEmployeesRoleComboBox = new main.SVGImage();
        sVGAddEmployeesFName = new main.SVGImage();
        sVGAddEmployeesLName = new main.SVGImage();
        sVGAddEmployeesRole = new main.SVGImage();
        sVGAddEmployeesPhone = new main.SVGImage();
        sVGAddEmployeesEmail = new main.SVGImage();
        sVGAddEmployeesAddress = new main.SVGImage();
        sVGAddEmployeesPasswordTextBox = new main.SVGImage();
        sVGAddEmployeesPassword = new main.SVGImage();
        sVGAddEmployeesForm = new main.SVGImage();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(null);
        setPreferredSize(new java.awt.Dimension(649, 426));
        setSize(new java.awt.Dimension(649, 426));
        setLayout(null);

        txtFName.setFont(new java.awt.Font("SF Pro Display", 0, 13)); // NOI18N
        txtFName.setForeground(new java.awt.Color(0, 0, 0));
        txtFName.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtFName.setBorder(null);
        add(txtFName);
        txtFName.setBounds(307, 20, 147, 17);

        txtLName.setFont(new java.awt.Font("SF Pro Display", 0, 13)); // NOI18N
        txtLName.setForeground(new java.awt.Color(0, 0, 0));
        txtLName.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtLName.setBorder(null);
        add(txtLName);
        txtLName.setBounds(307, 57, 147, 17);

        txtPhone.setFont(new java.awt.Font("SF Pro Display", 0, 13)); // NOI18N
        txtPhone.setForeground(new java.awt.Color(0, 0, 0));
        txtPhone.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtPhone.setBorder(null);
        txtPhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPhoneKeyTyped(evt);
            }
        });
        add(txtPhone);
        txtPhone.setBounds(307, 130, 147, 17);

        txtEmail.setFont(new java.awt.Font("SF Pro Display", 0, 13)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(0, 0, 0));
        txtEmail.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtEmail.setBorder(null);
        add(txtEmail);
        txtEmail.setBounds(307, 167, 147, 17);

        txtAddress.setFont(new java.awt.Font("SF Pro Display", 0, 13)); // NOI18N
        txtAddress.setForeground(new java.awt.Color(0, 0, 0));
        txtAddress.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtAddress.setBorder(null);
        add(txtAddress);
        txtAddress.setBounds(307, 204, 147, 17);

        txtPassword.setFont(new java.awt.Font("SF Pro Display", 0, 13)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(0, 0, 0));
        txtPassword.setBorder(null);
        add(txtPassword);
        txtPassword.setBounds(307, 241, 147, 17);

        cmbRole.setFont(new java.awt.Font("SF Pro Display", 0, 13)); // NOI18N
        cmbRole.setForeground(new java.awt.Color(0, 0, 0));
        cmbRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "General Farmworker", "Fruit Picker", "Waterer" }));
        cmbRole.setBorder(null);
        cmbRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRoleActionPerformed(evt);
            }
        });
        add(cmbRole);
        cmbRole.setBounds(301, 92, 160, 21);

        sVGAddBtn.setForeground(new java.awt.Color(0, 0, 0));
        sVGAddBtn.setText("sVGAddButton");
        sVGAddBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sVGAddBtnMouseClicked(evt);
            }
        });
        add(sVGAddBtn);
        sVGAddBtn.setBounds(432, 281, 39, 22);

        sVGAddEmployeesFNameTextBox.setForeground(new java.awt.Color(0, 0, 0));
        sVGAddEmployeesFNameTextBox.setText("sVGAddEmployeesFNameTextBox");
        sVGAddEmployeesFNameTextBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sVGAddEmployeesFNameTextBoxMouseClicked(evt);
            }
        });
        add(sVGAddEmployeesFNameTextBox);
        sVGAddEmployeesFNameTextBox.setBounds(301, 17, 160, 23);

        sVGAddEmployeesLNameTextBox.setForeground(new java.awt.Color(0, 0, 0));
        sVGAddEmployeesLNameTextBox.setText("sVGAddEmployeesLNameTextBox");
        sVGAddEmployeesLNameTextBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sVGAddEmployeesLNameTextBoxMouseClicked(evt);
            }
        });
        add(sVGAddEmployeesLNameTextBox);
        sVGAddEmployeesLNameTextBox.setBounds(301, 54, 160, 23);

        sVGAddEmployeesPhoneTextBox.setForeground(new java.awt.Color(0, 0, 0));
        sVGAddEmployeesPhoneTextBox.setText("sVGAddEmployeesPhoneTextBox");
        sVGAddEmployeesPhoneTextBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sVGAddEmployeesPhoneTextBoxMouseClicked(evt);
            }
        });
        add(sVGAddEmployeesPhoneTextBox);
        sVGAddEmployeesPhoneTextBox.setBounds(301, 127, 160, 23);

        sVGAddEmployeesEmailTextBox.setForeground(new java.awt.Color(0, 0, 0));
        sVGAddEmployeesEmailTextBox.setText("sVGAddEmployeesEmailTextBox");
        sVGAddEmployeesEmailTextBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sVGAddEmployeesEmailTextBoxMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sVGAddEmployeesEmailTextBoxMouseEntered(evt);
            }
        });
        add(sVGAddEmployeesEmailTextBox);
        sVGAddEmployeesEmailTextBox.setBounds(301, 164, 160, 23);

        sVGAddEmployeesAddressTextBox.setForeground(new java.awt.Color(0, 0, 0));
        sVGAddEmployeesAddressTextBox.setText("sVGAddEmployeesPassTextBox");
        sVGAddEmployeesAddressTextBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sVGAddEmployeesAddressTextBoxMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sVGAddEmployeesAddressTextBoxMouseEntered(evt);
            }
        });
        add(sVGAddEmployeesAddressTextBox);
        sVGAddEmployeesAddressTextBox.setBounds(301, 201, 160, 23);

        sVGAddEmployeesRoleComboBox.setForeground(new java.awt.Color(0, 0, 0));
        sVGAddEmployeesRoleComboBox.setText("sVGAddEmployeesRoleComboBox");
        sVGAddEmployeesRoleComboBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sVGAddEmployeesRoleComboBoxMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sVGAddEmployeesRoleComboBoxMouseEntered(evt);
            }
        });
        add(sVGAddEmployeesRoleComboBox);
        sVGAddEmployeesRoleComboBox.setBounds(301, 92, 160, 21);

        sVGAddEmployeesFName.setForeground(new java.awt.Color(0, 0, 0));
        sVGAddEmployeesFName.setText("sVGAddEmployeesFName");
        add(sVGAddEmployeesFName);
        sVGAddEmployeesFName.setBounds(30, 10, 431, 37);

        sVGAddEmployeesLName.setForeground(new java.awt.Color(0, 0, 0));
        sVGAddEmployeesLName.setText("sVGAddEmployeesLName");
        add(sVGAddEmployeesLName);
        sVGAddEmployeesLName.setBounds(30, 47, 431, 37);

        sVGAddEmployeesRole.setForeground(new java.awt.Color(0, 0, 0));
        sVGAddEmployeesRole.setText("sVGAddEmployeesRole");
        add(sVGAddEmployeesRole);
        sVGAddEmployeesRole.setBounds(30, 84, 431, 36);

        sVGAddEmployeesPhone.setForeground(new java.awt.Color(0, 0, 0));
        sVGAddEmployeesPhone.setText("sVGAddEmployeesPhone");
        add(sVGAddEmployeesPhone);
        sVGAddEmployeesPhone.setBounds(30, 120, 431, 37);

        sVGAddEmployeesEmail.setForeground(new java.awt.Color(0, 0, 0));
        sVGAddEmployeesEmail.setText("sVGAddEmployeesEmail");
        add(sVGAddEmployeesEmail);
        sVGAddEmployeesEmail.setBounds(30, 157, 431, 37);

        sVGAddEmployeesAddress.setForeground(new java.awt.Color(0, 0, 0));
        sVGAddEmployeesAddress.setText("sVGAddEmployeesAddress");
        add(sVGAddEmployeesAddress);
        sVGAddEmployeesAddress.setBounds(30, 194, 431, 37);

        sVGAddEmployeesPasswordTextBox.setForeground(new java.awt.Color(0, 0, 0));
        sVGAddEmployeesPasswordTextBox.setText("sVGAddEmployeesPassTextBox");
        sVGAddEmployeesPasswordTextBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sVGAddEmployeesPasswordTextBoxMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sVGAddEmployeesPasswordTextBoxMouseEntered(evt);
            }
        });
        add(sVGAddEmployeesPasswordTextBox);
        sVGAddEmployeesPasswordTextBox.setBounds(301, 238, 160, 23);

        sVGAddEmployeesPassword.setForeground(new java.awt.Color(0, 0, 0));
        sVGAddEmployeesPassword.setText("sVGAddEmployeesPassword");
        add(sVGAddEmployeesPassword);
        sVGAddEmployeesPassword.setBounds(30, 231, 431, 37);

        sVGAddEmployeesForm.setForeground(new java.awt.Color(0, 0, 0));
        sVGAddEmployeesForm.setText("sVGAddEmployeesForm");
        add(sVGAddEmployeesForm);
        sVGAddEmployeesForm.setBounds(20, 10, 451, 258);
    }// </editor-fold>//GEN-END:initComponents

    private void sVGAddEmployeesFNameTextBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sVGAddEmployeesFNameTextBoxMouseClicked
        txtFName.setVisible(true);
        txtFName.requestFocusInWindow();
    }//GEN-LAST:event_sVGAddEmployeesFNameTextBoxMouseClicked

    private void sVGAddEmployeesLNameTextBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sVGAddEmployeesLNameTextBoxMouseClicked
        txtLName.setVisible(true);
        txtLName.requestFocusInWindow();
    }//GEN-LAST:event_sVGAddEmployeesLNameTextBoxMouseClicked

    private void sVGAddEmployeesPhoneTextBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sVGAddEmployeesPhoneTextBoxMouseClicked
        txtPhone.setVisible(true);
        txtPhone.requestFocusInWindow();
    }//GEN-LAST:event_sVGAddEmployeesPhoneTextBoxMouseClicked

    private void sVGAddEmployeesEmailTextBoxMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sVGAddEmployeesEmailTextBoxMouseEntered
        
    }//GEN-LAST:event_sVGAddEmployeesEmailTextBoxMouseEntered

    private void sVGAddEmployeesAddressTextBoxMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sVGAddEmployeesAddressTextBoxMouseEntered
        
    }//GEN-LAST:event_sVGAddEmployeesAddressTextBoxMouseEntered

    private void cmbRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRoleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbRoleActionPerformed

    private void sVGAddEmployeesRoleComboBoxMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sVGAddEmployeesRoleComboBoxMouseEntered

    }//GEN-LAST:event_sVGAddEmployeesRoleComboBoxMouseEntered

    private void sVGAddBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sVGAddBtnMouseClicked
        String fname = txtFName.getText();
        String lname = txtLName.getText();
        int phone = Integer.parseInt(txtPhone.getText());
        String email = txtEmail.getText();
        String address = txtAddress.getText();
        String role = (String) cmbRole.getSelectedItem();
        String pass = txtPassword.getText();
        
        // Add to the database
        Connection conn = null;
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/LittleGroot", "root" , "toor");
            
            Statement st = conn.createStatement();
            
            int updatedRows = st.executeUpdate("INSERT INTO Employee(FName, LName, EmpRole, Phone, Email, Address, Pass) VALUES ('" + fname + "' ,'" + lname + "' ,'" + role + "' ,'" + phone + "' ,'" + email + "' ,'" + address + "' ,'" + pass + "');");
            if(updatedRows > 0) {
                // Clear the textboxes
                txtFName.setText("");
                txtLName.setText("");
                txtPhone.setText("");
                txtEmail.setText("");
                txtAddress.setText("");
                txtPassword.setText("");
                cmbRole.setSelectedIndex(0);
                // Show message
                JOptionPane.showMessageDialog(null, "Account added successfully!");
            } else {
                JOptionPane.showMessageDialog(null, "Failed to add account");
            }
            
        } catch (ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(null, "Database Connection Error");
        } finally {
            if (conn != null) {
                try {
                    conn.close();
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(null, "Failed to close connection");
                }
            }
        }
    }//GEN-LAST:event_sVGAddBtnMouseClicked

    private void sVGAddEmployeesPasswordTextBoxMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sVGAddEmployeesPasswordTextBoxMouseEntered
        
    }//GEN-LAST:event_sVGAddEmployeesPasswordTextBoxMouseEntered

    private void sVGAddEmployeesPasswordTextBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sVGAddEmployeesPasswordTextBoxMouseClicked
        txtPassword.setVisible(true);
        txtPassword.requestFocusInWindow();
    }//GEN-LAST:event_sVGAddEmployeesPasswordTextBoxMouseClicked

    private void sVGAddEmployeesRoleComboBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sVGAddEmployeesRoleComboBoxMouseClicked
        cmbRole.setVisible(true);
        cmbRole.requestFocusInWindow();
    }//GEN-LAST:event_sVGAddEmployeesRoleComboBoxMouseClicked

    private void sVGAddEmployeesEmailTextBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sVGAddEmployeesEmailTextBoxMouseClicked
        txtEmail.setVisible(true);
        txtEmail.requestFocusInWindow();
    }//GEN-LAST:event_sVGAddEmployeesEmailTextBoxMouseClicked

    private void sVGAddEmployeesAddressTextBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sVGAddEmployeesAddressTextBoxMouseClicked
        txtAddress.setVisible(true);
        txtAddress.requestFocusInWindow();
    }//GEN-LAST:event_sVGAddEmployeesAddressTextBoxMouseClicked

    private void txtPhoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPhoneKeyTyped
        // Only accepts 10 digits
        char c = evt.getKeyChar();
        if (!((c >= '0') && (c <= '9') ||
           (c == KeyEvent.VK_BACK_SPACE) ||
           (c == KeyEvent.VK_DELETE))) {
          evt.consume();  // ignore event
        }
        if (txtPhone.getText().length() >= 10 ) { // limit textfield to 10 characters
            evt.consume();
        }
    }//GEN-LAST:event_txtPhoneKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbRole;
    private main.SVGImage sVGAddBtn;
    private main.SVGImage sVGAddEmployeesAddress;
    private main.SVGImage sVGAddEmployeesAddressTextBox;
    private main.SVGImage sVGAddEmployeesEmail;
    private main.SVGImage sVGAddEmployeesEmailTextBox;
    private main.SVGImage sVGAddEmployeesFName;
    private main.SVGImage sVGAddEmployeesFNameTextBox;
    private main.SVGImage sVGAddEmployeesForm;
    private main.SVGImage sVGAddEmployeesLName;
    private main.SVGImage sVGAddEmployeesLNameTextBox;
    private main.SVGImage sVGAddEmployeesPassword;
    private main.SVGImage sVGAddEmployeesPasswordTextBox;
    private main.SVGImage sVGAddEmployeesPhone;
    private main.SVGImage sVGAddEmployeesPhoneTextBox;
    private main.SVGImage sVGAddEmployeesRole;
    private main.SVGImage sVGAddEmployeesRoleComboBox;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFName;
    private javax.swing.JTextField txtLName;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtPhone;
    // End of variables declaration//GEN-END:variables

}
