/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package uis;

/**
 *
 * @author gamitha
 */
public class AddFieldMetrics extends javax.swing.JPanel {

    /**
     * Creates new form AddFieldMetrics
     */
    public AddFieldMetrics() {
        initComponents();
        
        // Set SVGs
        sVGAddBtn.setSvgImage("./svgcomponents/AddBtn.svg", 39, 22);
        sVGAddFieldMetricsForm.setSvgImage("./svgcomponents/AddFieldMetricsForm.svg", 451, 176);
        sVGAddFieldMetricsField.setSvgImage("./svgcomponents/AddFieldMetricsField.svg", 431, 36);
        sVGAddFieldMetricsSoilPh.setSvgImage("./svgcomponents/AddFieldMetricsSoilPh.svg", 431, 36);
        sVGAddFieldMetricsSoilMoisture.setSvgImage("./svgcomponents/AddFieldMetricsSoilMoisture.svg", 431, 52);
        sVGAddFieldMetricsLightIntensity.setSvgImage("./svgcomponents/AddFieldMetricsLightIntensity.svg", 431, 52);
        sVGAddFieldMetricsFieldComboBox.setSvgImage("./svgcomponents/AddFieldMetricsFieldComboBox.svg", 160, 21);
        sVGStepper1.setSvgImage("./svgcomponents/Stepper.svg", 53, 24);
        sVGStepperWithPercentage1.setSvgImage("./svgcomponents/StepperWithPercentage.svg", 72, 24);
        sVGAddFieldMetricsLightIntensityTextBox.setSvgImage("./svgcomponents/AddFieldMetricsLightIntensityTextBox.svg", 160, 23);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sVGAddFieldMetricsFieldComboBox = new main.SVGImage();
        sVGStepper1 = new main.SVGImage();
        sVGStepperWithPercentage1 = new main.SVGImage();
        sVGAddFieldMetricsLightIntensityTextBox = new main.SVGImage();
        sVGAddFieldMetricsField = new main.SVGImage();
        sVGAddFieldMetricsSoilPh = new main.SVGImage();
        sVGAddFieldMetricsSoilMoisture = new main.SVGImage();
        sVGAddFieldMetricsLightIntensity = new main.SVGImage();
        sVGAddBtn = new main.SVGImage();
        sVGAddFieldMetricsForm = new main.SVGImage();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(null);
        setSize(new java.awt.Dimension(649, 426));
        setLayout(null);

        sVGAddFieldMetricsFieldComboBox.setForeground(new java.awt.Color(0, 0, 0));
        sVGAddFieldMetricsFieldComboBox.setText("sVGAddFieldMetricsFieldComboBox");
        add(sVGAddFieldMetricsFieldComboBox);
        sVGAddFieldMetricsFieldComboBox.setBounds(301, 18, 160, 21);

        sVGStepper1.setForeground(new java.awt.Color(0, 0, 0));
        sVGStepper1.setText("sVGStepper1");
        add(sVGStepper1);
        sVGStepper1.setBounds(408, 52, 53, 24);

        sVGStepperWithPercentage1.setForeground(new java.awt.Color(0, 0, 0));
        sVGStepperWithPercentage1.setText("sVGStepperWithPercentage1");
        add(sVGStepperWithPercentage1);
        sVGStepperWithPercentage1.setBounds(389, 96, 72, 24);

        sVGAddFieldMetricsLightIntensityTextBox.setForeground(new java.awt.Color(0, 0, 0));
        sVGAddFieldMetricsLightIntensityTextBox.setText("sVGAddFieldMetricsLightIntensityTextBox");
        add(sVGAddFieldMetricsLightIntensityTextBox);
        sVGAddFieldMetricsLightIntensityTextBox.setBounds(301, 149, 160, 23);

        sVGAddFieldMetricsField.setForeground(new java.awt.Color(0, 0, 0));
        sVGAddFieldMetricsField.setText("sVGAddFieldMetricsField");
        add(sVGAddFieldMetricsField);
        sVGAddFieldMetricsField.setBounds(30, 10, 431, 36);

        sVGAddFieldMetricsSoilPh.setForeground(new java.awt.Color(0, 0, 0));
        sVGAddFieldMetricsSoilPh.setText("sVGAddFieldMetricsSoilPh");
        add(sVGAddFieldMetricsSoilPh);
        sVGAddFieldMetricsSoilPh.setBounds(30, 46, 431, 36);

        sVGAddFieldMetricsSoilMoisture.setForeground(new java.awt.Color(0, 0, 0));
        sVGAddFieldMetricsSoilMoisture.setText("sVGAddFieldMetricsSoilMoisture");
        sVGAddFieldMetricsSoilMoisture.setToolTipText("");
        add(sVGAddFieldMetricsSoilMoisture);
        sVGAddFieldMetricsSoilMoisture.setBounds(30, 82, 431, 52);

        sVGAddFieldMetricsLightIntensity.setForeground(new java.awt.Color(0, 0, 0));
        sVGAddFieldMetricsLightIntensity.setText("sVGAddFieldMetricsLightIntensity");
        add(sVGAddFieldMetricsLightIntensity);
        sVGAddFieldMetricsLightIntensity.setBounds(30, 134, 431, 52);

        sVGAddBtn.setForeground(new java.awt.Color(0, 0, 0));
        sVGAddBtn.setText("sVGAddBtn");
        add(sVGAddBtn);
        sVGAddBtn.setBounds(432, 201, 39, 22);

        sVGAddFieldMetricsForm.setForeground(new java.awt.Color(0, 0, 0));
        sVGAddFieldMetricsForm.setText("sVGAddFieldMetricsForm");
        add(sVGAddFieldMetricsForm);
        sVGAddFieldMetricsForm.setBounds(20, 10, 451, 176);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private main.SVGImage sVGAddBtn;
    private main.SVGImage sVGAddFieldMetricsField;
    private main.SVGImage sVGAddFieldMetricsFieldComboBox;
    private main.SVGImage sVGAddFieldMetricsForm;
    private main.SVGImage sVGAddFieldMetricsLightIntensity;
    private main.SVGImage sVGAddFieldMetricsLightIntensityTextBox;
    private main.SVGImage sVGAddFieldMetricsSoilMoisture;
    private main.SVGImage sVGAddFieldMetricsSoilPh;
    private main.SVGImage sVGStepper1;
    private main.SVGImage sVGStepperWithPercentage1;
    // End of variables declaration//GEN-END:variables
}
