/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package uis;

/**
 *
 * @author gamitha
 */
public class AddInventory extends javax.swing.JPanel {

    /**
     * Creates new form AddInventory
     */
    public AddInventory() {
        initComponents();
        
        sVGAddBtn1.setSvgImage("./svgcomponents/AddBtn.svg", 39, 22);
        sVGAddInventoryForm.setSvgImage("./svgcomponents/AddInventoryForm.svg", 451, 72);
        sVGAddInventoryItem.setSvgImage("./svgcomponents/AddInventoryItem.svg", 431, 36);
        sVGAddInventoryItemComboBox.setSvgImage("./svgcomponents/AddInventoryItemComboBox.svg", 160, 21);
        sVGAddInventoryQty.setSvgImage("./svgcomponents/AddInventoryQty.svg", 431, 36);
        sVGStepperWithKg.setSvgImage("./svgcomponents/StepperWithKg.svg", 74, 24);
        
        sVGAddBtn2.setSvgImage("./svgcomponents/AddBtn.svg", 39, 22);
        sVGAddInventoryNewForm.setSvgImage("./svgcomponents/AddInventoryNewForm.svg", 451, 111);
        sVGAddInventoryNewItem.setSvgImage("./svgcomponents/AddInventoryNewItem.svg", 431, 37);
        sVGAddInventoryNewItemTextBox.setSvgImage("./svgcomponents/AddInventoryNewItemTextBox.svg", 160, 23);
        sVGAddInventoryNewItemID.setSvgImage("./svgcomponents/AddInventoryNewItemID.svg", 431, 37);
        sVGAddInventoryNewItemIDTextBox.setSvgImage("./svgcomponents/AddInventoryNewItemIDTextBox.svg", 160, 23);
        sVGAddInventoryNewUnit.setSvgImage("./svgcomponents/AddInventoryNewUnit.svg", 431, 37);
        sVGAddInventoryNewUnitTextBox.setSvgImage("./svgcomponents/AddInventoryNewUnitTextBox.svg", 160, 23);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sVGAddInventoryItemComboBox = new main.SVGImage();
        sVGAddInventoryItem = new main.SVGImage();
        sVGAddInventoryQty = new main.SVGImage();
        sVGStepperWithKg = new main.SVGImage();
        sVGAddInventoryForm = new main.SVGImage();
        sVGAddBtn1 = new main.SVGImage();
        lblNewItem = new javax.swing.JLabel();
        sVGAddInventoryNewItemTextBox = new main.SVGImage();
        sVGAddInventoryNewItemIDTextBox = new main.SVGImage();
        sVGAddInventoryNewUnitTextBox = new main.SVGImage();
        sVGAddInventoryNewItem = new main.SVGImage();
        sVGAddInventoryNewItemID = new main.SVGImage();
        sVGAddInventoryNewUnit = new main.SVGImage();
        sVGAddInventoryNewForm = new main.SVGImage();
        sVGAddBtn2 = new main.SVGImage();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(null);
        setSize(new java.awt.Dimension(649, 426));
        setLayout(null);

        sVGAddInventoryItemComboBox.setForeground(new java.awt.Color(0, 0, 0));
        sVGAddInventoryItemComboBox.setText("sVGAddInventoryItemComboBox");
        add(sVGAddInventoryItemComboBox);
        sVGAddInventoryItemComboBox.setBounds(301, 18, 160, 21);

        sVGAddInventoryItem.setForeground(new java.awt.Color(0, 0, 0));
        sVGAddInventoryItem.setText("sVGAddInventoryItem");
        add(sVGAddInventoryItem);
        sVGAddInventoryItem.setBounds(30, 10, 431, 36);

        sVGAddInventoryQty.setForeground(new java.awt.Color(0, 0, 0));
        sVGAddInventoryQty.setText("sVGAddInventoryQty");
        add(sVGAddInventoryQty);
        sVGAddInventoryQty.setBounds(30, 46, 431, 36);

        sVGStepperWithKg.setForeground(new java.awt.Color(0, 0, 0));
        sVGStepperWithKg.setText("sVGStepperWithKg");
        add(sVGStepperWithKg);
        sVGStepperWithKg.setBounds(387, 52, 74, 24);

        sVGAddInventoryForm.setForeground(new java.awt.Color(0, 0, 0));
        sVGAddInventoryForm.setText("sVGAddInventoryForm");
        add(sVGAddInventoryForm);
        sVGAddInventoryForm.setBounds(20, 10, 451, 72);

        sVGAddBtn1.setForeground(new java.awt.Color(0, 0, 0));
        sVGAddBtn1.setText("sVGAddBtn1");
        add(sVGAddBtn1);
        sVGAddBtn1.setBounds(432, 97, 39, 22);

        lblNewItem.setFont(new java.awt.Font("SF Pro Text", 1, 13)); // NOI18N
        lblNewItem.setForeground(new java.awt.Color(0, 0, 0));
        lblNewItem.setText("New Item");
        add(lblNewItem);
        lblNewItem.setBounds(20, 149, 70, 16);

        sVGAddInventoryNewItemTextBox.setForeground(new java.awt.Color(0, 0, 0));
        sVGAddInventoryNewItemTextBox.setText("sVGAddInventoryNewItemTextBox");
        add(sVGAddInventoryNewItemTextBox);
        sVGAddInventoryNewItemTextBox.setBounds(301, 182, 160, 23);

        sVGAddInventoryNewItemIDTextBox.setForeground(new java.awt.Color(0, 0, 0));
        sVGAddInventoryNewItemIDTextBox.setText("sVGAddInventoryNewItemIDTextBox");
        add(sVGAddInventoryNewItemIDTextBox);
        sVGAddInventoryNewItemIDTextBox.setBounds(301, 219, 160, 23);

        sVGAddInventoryNewUnitTextBox.setForeground(new java.awt.Color(0, 0, 0));
        sVGAddInventoryNewUnitTextBox.setText("sVGAddInventoryNewUnitTextBox");
        add(sVGAddInventoryNewUnitTextBox);
        sVGAddInventoryNewUnitTextBox.setBounds(301, 256, 160, 23);

        sVGAddInventoryNewItem.setForeground(new java.awt.Color(0, 0, 0));
        sVGAddInventoryNewItem.setText("sVGAddInventoryNewItem");
        add(sVGAddInventoryNewItem);
        sVGAddInventoryNewItem.setBounds(30, 175, 431, 37);

        sVGAddInventoryNewItemID.setForeground(new java.awt.Color(0, 0, 0));
        sVGAddInventoryNewItemID.setText("sVGAddInventoryNewItemID");
        add(sVGAddInventoryNewItemID);
        sVGAddInventoryNewItemID.setBounds(30, 212, 431, 37);

        sVGAddInventoryNewUnit.setForeground(new java.awt.Color(0, 0, 0));
        sVGAddInventoryNewUnit.setText("sVGAddInventoryNewUnit");
        add(sVGAddInventoryNewUnit);
        sVGAddInventoryNewUnit.setBounds(30, 249, 431, 37);

        sVGAddInventoryNewForm.setForeground(new java.awt.Color(0, 0, 0));
        sVGAddInventoryNewForm.setText("sVGAddInventoryNewForm");
        add(sVGAddInventoryNewForm);
        sVGAddInventoryNewForm.setBounds(20, 175, 451, 111);

        sVGAddBtn2.setForeground(new java.awt.Color(0, 0, 0));
        sVGAddBtn2.setText("sVGAddBtn2");
        add(sVGAddBtn2);
        sVGAddBtn2.setBounds(432, 301, 39, 22);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblNewItem;
    private main.SVGImage sVGAddBtn1;
    private main.SVGImage sVGAddBtn2;
    private main.SVGImage sVGAddInventoryForm;
    private main.SVGImage sVGAddInventoryItem;
    private main.SVGImage sVGAddInventoryItemComboBox;
    private main.SVGImage sVGAddInventoryNewForm;
    private main.SVGImage sVGAddInventoryNewItem;
    private main.SVGImage sVGAddInventoryNewItemID;
    private main.SVGImage sVGAddInventoryNewItemIDTextBox;
    private main.SVGImage sVGAddInventoryNewItemTextBox;
    private main.SVGImage sVGAddInventoryNewUnit;
    private main.SVGImage sVGAddInventoryNewUnitTextBox;
    private main.SVGImage sVGAddInventoryQty;
    private main.SVGImage sVGStepperWithKg;
    // End of variables declaration//GEN-END:variables
}
