/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package uis;

/**
 *
 * @author gamitha
 */
public class AddTasks extends javax.swing.JPanel {

    /**
     * Creates new form AddTasks
     */
    public AddTasks() {
        initComponents();
        
        sVGAddBtn.setSvgImage("./svgcomponents/AddBtn.svg", 39, 22);
        sVGAddTasksTaskTextBox.setSvgImage("./svgcomponents/AddTasksTaskTextBox.svg", 160, 23);
        sVGAddTasksCategoryComboBox.setSvgImage("./svgcomponents/AddTasksCategoryComboBox.svg", 160, 21);
        sVGStepper051.setSvgImage("./svgcomponents/Stepper05.svg", 42, 24);
        sVGStepper101.setSvgImage("./svgcomponents/Stepper10.svg", 40, 24);
        sVGStepper20241.setSvgImage("./svgcomponents/Stepper2024.svg", 58, 24);
        sVGAddTasksTask.setSvgImage("./svgcomponents/AddTasksTask.svg", 431, 37);
        sVGAddTasksCategory.setSvgImage("./svgcomponents/AddTasksCategory.svg", 431, 36);
        sVGAddTasksDate.setSvgImage("./svgcomponents/AddTasksDate.svg", 431, 36);
        sVGAddTasksForm.setSvgImage("./svgcomponents/AddTasksForm.svg", 451, 109);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sVGAddBtn = new main.SVGImage();
        sVGAddTasksTaskTextBox = new main.SVGImage();
        sVGAddTasksCategoryComboBox = new main.SVGImage();
        sVGStepper051 = new main.SVGImage();
        sVGStepper101 = new main.SVGImage();
        sVGStepper20241 = new main.SVGImage();
        sVGAddTasksTask = new main.SVGImage();
        sVGAddTasksCategory = new main.SVGImage();
        sVGAddTasksDate = new main.SVGImage();
        sVGAddTasksForm = new main.SVGImage();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(null);
        setSize(new java.awt.Dimension(649, 426));
        setLayout(null);

        sVGAddBtn.setForeground(new java.awt.Color(0, 0, 0));
        sVGAddBtn.setText("sVGAddBtn");
        add(sVGAddBtn);
        sVGAddBtn.setBounds(432, 134, 39, 22);

        sVGAddTasksTaskTextBox.setForeground(new java.awt.Color(0, 0, 0));
        sVGAddTasksTaskTextBox.setText("sVGAddTasksTaskTextBox");
        add(sVGAddTasksTaskTextBox);
        sVGAddTasksTaskTextBox.setBounds(301, 17, 160, 23);

        sVGAddTasksCategoryComboBox.setForeground(new java.awt.Color(0, 0, 0));
        sVGAddTasksCategoryComboBox.setText("sVGAddTasksCategoryComboBox");
        add(sVGAddTasksCategoryComboBox);
        sVGAddTasksCategoryComboBox.setBounds(301, 55, 160, 21);

        sVGStepper051.setForeground(new java.awt.Color(0, 0, 0));
        sVGStepper051.setText("sVGStepper05");
        add(sVGStepper051);
        sVGStepper051.setBounds(301, 89, 42, 24);

        sVGStepper101.setForeground(new java.awt.Color(0, 0, 0));
        sVGStepper101.setText("sVGStepper101");
        add(sVGStepper101);
        sVGStepper101.setBounds(353, 89, 40, 24);

        sVGStepper20241.setForeground(new java.awt.Color(0, 0, 0));
        sVGStepper20241.setText("sVGStepper20241");
        add(sVGStepper20241);
        sVGStepper20241.setBounds(403, 89, 58, 24);

        sVGAddTasksTask.setForeground(new java.awt.Color(0, 0, 0));
        sVGAddTasksTask.setText("sVGAddTasksTask");
        add(sVGAddTasksTask);
        sVGAddTasksTask.setBounds(30, 10, 431, 37);

        sVGAddTasksCategory.setForeground(new java.awt.Color(0, 0, 0));
        sVGAddTasksCategory.setText("sVGAddTasksCategory");
        add(sVGAddTasksCategory);
        sVGAddTasksCategory.setBounds(30, 47, 431, 36);

        sVGAddTasksDate.setForeground(new java.awt.Color(0, 0, 0));
        sVGAddTasksDate.setText("sVGAddTasksDate");
        add(sVGAddTasksDate);
        sVGAddTasksDate.setBounds(30, 83, 431, 36);

        sVGAddTasksForm.setForeground(new java.awt.Color(0, 0, 0));
        sVGAddTasksForm.setText("sVGAddTasksForm");
        add(sVGAddTasksForm);
        sVGAddTasksForm.setBounds(20, 10, 451, 109);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private main.SVGImage sVGAddBtn;
    private main.SVGImage sVGAddTasksCategory;
    private main.SVGImage sVGAddTasksCategoryComboBox;
    private main.SVGImage sVGAddTasksDate;
    private main.SVGImage sVGAddTasksForm;
    private main.SVGImage sVGAddTasksTask;
    private main.SVGImage sVGAddTasksTaskTextBox;
    private main.SVGImage sVGStepper051;
    private main.SVGImage sVGStepper101;
    private main.SVGImage sVGStepper20241;
    // End of variables declaration//GEN-END:variables
}
