/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package uis;

/**
 *
 * @author gamitha
 */
public class AddTransactions extends javax.swing.JPanel {

    /**
     * Creates new form AddTransactions
     */
    public AddTransactions() {
        initComponents();
        
        // Set SVGs
        sVGAddTransactionsForm.setSvgImage("./svgcomponents/AddTransactionsForm.svg", 451, 145);
        sVGAddTransactionsType.setSvgImage("./svgcomponents/AddTransactionsType.svg", 431, 36);
        sVGAddTransactionsCategory.setSvgImage("./svgcomponents/AddTransactionsCategory.svg", 431, 36);
        sVGAddTransactionsDate.setSvgImage("./svgcomponents/AddTransactionsDate.svg", 431, 36);
        sVGAddTransactionsAmount.setSvgImage("./svgcomponents/AddTransactionsAmount.svg", 431, 36);
        sVGAddBtn.setSvgImage("./svgcomponents/AddBtn.svg", 39, 22);
        sVGAddTransactionsCategoryComboBox.setSvgImage("./svgcomponents/AddTransactionsCategoryComboBox.svg", 160, 21);
        sVGAddTransactionsAmountTextBox.setSvgImage("./svgcomponents/AddTransactionsAmountTextBox.svg", 160, 23);
        sVGStepper051.setSvgImage("./svgcomponents/Stepper05.svg", 42, 24);
        sVGStepper101.setSvgImage("./svgcomponents/Stepper10.svg", 40, 24);
        sVGStepper20241.setSvgImage("./svgcomponents/Stepper2024.svg", 58, 24);
        sVGAddTransactionTypeIncomeRadioBtn.setSvgImage("./svgcomponents/RadioBtnSelected.svg", 14, 14);
        sVGAddTransactionTypeExpenseRadioBtn.setSvgImage("./svgcomponents/RadioBtn.svg", 14, 14);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sVGAddBtn = new main.SVGImage();
        sVGAddTransactionsCategoryComboBox = new main.SVGImage();
        sVGAddTransactionsAmountTextBox = new main.SVGImage();
        sVGStepper051 = new main.SVGImage();
        sVGStepper101 = new main.SVGImage();
        sVGStepper20241 = new main.SVGImage();
        sVGAddTransactionTypeIncomeRadioBtn = new main.SVGImage();
        sVGAddTransactionTypeExpenseRadioBtn = new main.SVGImage();
        lblIncome = new javax.swing.JLabel();
        lblExpense = new javax.swing.JLabel();
        sVGAddTransactionsType = new main.SVGImage();
        sVGAddTransactionsCategory = new main.SVGImage();
        sVGAddTransactionsDate = new main.SVGImage();
        sVGAddTransactionsAmount = new main.SVGImage();
        sVGAddTransactionsForm = new main.SVGImage();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(null);
        setSize(new java.awt.Dimension(649, 426));
        setLayout(null);

        sVGAddBtn.setForeground(new java.awt.Color(0, 0, 0));
        sVGAddBtn.setText("sVGAddBtn");
        add(sVGAddBtn);
        sVGAddBtn.setBounds(432, 170, 39, 22);

        sVGAddTransactionsCategoryComboBox.setForeground(new java.awt.Color(0, 0, 0));
        sVGAddTransactionsCategoryComboBox.setText("sVGAddTransactionsCategoryComboBox");
        add(sVGAddTransactionsCategoryComboBox);
        sVGAddTransactionsCategoryComboBox.setBounds(301, 54, 160, 21);

        sVGAddTransactionsAmountTextBox.setForeground(new java.awt.Color(0, 0, 0));
        sVGAddTransactionsAmountTextBox.setText("sVGAddTransactionsAmountTextBox");
        add(sVGAddTransactionsAmountTextBox);
        sVGAddTransactionsAmountTextBox.setBounds(301, 125, 160, 23);

        sVGStepper051.setForeground(new java.awt.Color(0, 0, 0));
        sVGStepper051.setText("sVGStepper051");
        add(sVGStepper051);
        sVGStepper051.setBounds(301, 88, 42, 24);

        sVGStepper101.setForeground(new java.awt.Color(0, 0, 0));
        sVGStepper101.setText("sVGStepper101");
        add(sVGStepper101);
        sVGStepper101.setBounds(353, 88, 40, 24);

        sVGStepper20241.setForeground(new java.awt.Color(0, 0, 0));
        sVGStepper20241.setText("sVGStepper20241");
        add(sVGStepper20241);
        sVGStepper20241.setBounds(403, 88, 58, 24);

        sVGAddTransactionTypeIncomeRadioBtn.setForeground(new java.awt.Color(0, 0, 0));
        sVGAddTransactionTypeIncomeRadioBtn.setText("sVGAddTransactionTypeIncomeRadioBtn");
        add(sVGAddTransactionTypeIncomeRadioBtn);
        sVGAddTransactionTypeIncomeRadioBtn.setBounds(308, 21, 14, 14);

        sVGAddTransactionTypeExpenseRadioBtn.setForeground(new java.awt.Color(0, 0, 0));
        sVGAddTransactionTypeExpenseRadioBtn.setText("sVGAddTransactionTypeExpenseRadioBtn");
        add(sVGAddTransactionTypeExpenseRadioBtn);
        sVGAddTransactionTypeExpenseRadioBtn.setBounds(389, 21, 14, 14);

        lblIncome.setFont(new java.awt.Font("SF Pro Text", 0, 13)); // NOI18N
        lblIncome.setForeground(new java.awt.Color(0, 0, 0));
        lblIncome.setText("Income");
        add(lblIncome);
        lblIncome.setBounds(328, 20, 45, 16);

        lblExpense.setFont(new java.awt.Font("SF Pro Text", 0, 13)); // NOI18N
        lblExpense.setForeground(new java.awt.Color(0, 0, 0));
        lblExpense.setText("Expense");
        add(lblExpense);
        lblExpense.setBounds(409, 20, 52, 16);

        sVGAddTransactionsType.setForeground(new java.awt.Color(0, 0, 0));
        sVGAddTransactionsType.setText("sVGAddTransactionsType");
        add(sVGAddTransactionsType);
        sVGAddTransactionsType.setBounds(30, 10, 431, 36);

        sVGAddTransactionsCategory.setForeground(new java.awt.Color(0, 0, 0));
        sVGAddTransactionsCategory.setText("sVGAddTransactionsCategory");
        add(sVGAddTransactionsCategory);
        sVGAddTransactionsCategory.setBounds(30, 46, 431, 36);

        sVGAddTransactionsDate.setForeground(new java.awt.Color(0, 0, 0));
        sVGAddTransactionsDate.setText("sVGAddTransactionsDate");
        add(sVGAddTransactionsDate);
        sVGAddTransactionsDate.setBounds(30, 82, 431, 36);

        sVGAddTransactionsAmount.setForeground(new java.awt.Color(0, 0, 0));
        sVGAddTransactionsAmount.setText("sVGAddTransactionsAmount");
        add(sVGAddTransactionsAmount);
        sVGAddTransactionsAmount.setBounds(30, 118, 431, 36);

        sVGAddTransactionsForm.setForeground(new java.awt.Color(0, 0, 0));
        sVGAddTransactionsForm.setText("sVGAddTransactionsForm");
        add(sVGAddTransactionsForm);
        sVGAddTransactionsForm.setBounds(20, 10, 451, 145);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblExpense;
    private javax.swing.JLabel lblIncome;
    private main.SVGImage sVGAddBtn;
    private main.SVGImage sVGAddTransactionTypeExpenseRadioBtn;
    private main.SVGImage sVGAddTransactionTypeIncomeRadioBtn;
    private main.SVGImage sVGAddTransactionsAmount;
    private main.SVGImage sVGAddTransactionsAmountTextBox;
    private main.SVGImage sVGAddTransactionsCategory;
    private main.SVGImage sVGAddTransactionsCategoryComboBox;
    private main.SVGImage sVGAddTransactionsDate;
    private main.SVGImage sVGAddTransactionsForm;
    private main.SVGImage sVGAddTransactionsType;
    private main.SVGImage sVGStepper051;
    private main.SVGImage sVGStepper101;
    private main.SVGImage sVGStepper20241;
    // End of variables declaration//GEN-END:variables
}
