/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package uis;

import javax.swing.ImageIcon;
import java.awt.Image;

/**
 *
 * @author gamitha
 */
public class AllFields extends javax.swing.JPanel {

    /**
     * Creates new form AllFields
     */
    public AllFields() {
        initComponents();
        sVGSalesGraph.setSvgImage("./svgcomponents/SalesGraph.svg", 292, 183);
        sVGYieldGraph.setSvgImage("./svgcomponents/YieldGraph.svg", 292, 183);
        addImageToLabel();
    }
    
    private void addImageToLabel() {
        //pngTomato
        try {
            // Get the image
            java.net.URL imgURL = getClass().getResource("/pngcomponents/Tomato.png");
            ImageIcon icon = new ImageIcon(imgURL);

            // Scale the image
            Image image = icon.getImage();
            Image newimg = image.getScaledInstance(188, 112, java.awt.Image.SCALE_SMOOTH); // Scale it the smooth way 
            icon = new ImageIcon(newimg);  // Transform it back

            // Add the image to the label
            pngTomato.setIcon(icon);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        
        //pngCorn
        try {
            // Get the image
            java.net.URL imgURL = getClass().getResource("/pngcomponents/Corn.png");
            ImageIcon icon = new ImageIcon(imgURL);

            // Scale the image
            Image image = icon.getImage();
            Image newimg = image.getScaledInstance(188, 112, java.awt.Image.SCALE_SMOOTH); // Scale it the smooth way 
            icon = new ImageIcon(newimg);  // Transform it back

            // Add the image to the label
            pngCorn.setIcon(icon);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        
        //pngApple
        try {
            // Get the image
            java.net.URL imgURL = getClass().getResource("/pngcomponents/Apple.png");
            ImageIcon icon = new ImageIcon(imgURL);

            // Scale the image
            Image image = icon.getImage();
            Image newimg = image.getScaledInstance(188, 112, java.awt.Image.SCALE_SMOOTH); // Scale it the smooth way 
            icon = new ImageIcon(newimg);  // Transform it back

            // Add the image to the label
            pngApple.setIcon(icon);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        
        //pngCarrot
        try {
            // Get the image
            java.net.URL imgURL = getClass().getResource("/pngcomponents/Carrot.png");
            ImageIcon icon = new ImageIcon(imgURL);

            // Scale the image
            Image image = icon.getImage();
            Image newimg = image.getScaledInstance(188, 112, java.awt.Image.SCALE_SMOOTH); // Scale it the smooth way 
            icon = new ImageIcon(newimg);  // Transform it back

            // Add the image to the label
            pngCarrot.setIcon(icon);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        
        //pngOrange
        try {
            // Get the image
            java.net.URL imgURL = getClass().getResource("/pngcomponents/Orange.png");
            ImageIcon icon = new ImageIcon(imgURL);

            // Scale the image
            Image image = icon.getImage();
            Image newimg = image.getScaledInstance(188, 112, java.awt.Image.SCALE_SMOOTH); // Scale it the smooth way 
            icon = new ImageIcon(newimg);  // Transform it back

            // Add the image to the label
            pngOrange.setIcon(icon);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        
        //pngMango
        try {
            // Get the image
            java.net.URL imgURL = getClass().getResource("/pngcomponents/Mango.png");
            ImageIcon icon = new ImageIcon(imgURL);

            // Scale the image
            Image image = icon.getImage();
            Image newimg = image.getScaledInstance(188, 112, java.awt.Image.SCALE_SMOOTH); // Scale it the smooth way 
            icon = new ImageIcon(newimg);  // Transform it back

            // Add the image to the label
            pngMango.setIcon(icon);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sVGSalesGraph = new main.SVGImage();
        sVGYieldGraph = new main.SVGImage();
        pngTomato = new javax.swing.JLabel();
        pngCorn = new javax.swing.JLabel();
        pngApple = new javax.swing.JLabel();
        lblTomato = new javax.swing.JLabel();
        lblTomatoAcre = new javax.swing.JLabel();
        lblCorn = new javax.swing.JLabel();
        lblCornAcre = new javax.swing.JLabel();
        lblAppleAcre = new javax.swing.JLabel();
        lblApple = new javax.swing.JLabel();
        lblCarrotAcre = new javax.swing.JLabel();
        lblCarrot = new javax.swing.JLabel();
        lblOrange = new javax.swing.JLabel();
        lblOrangeAcre = new javax.swing.JLabel();
        lblMango = new javax.swing.JLabel();
        lblMangoAcre = new javax.swing.JLabel();
        pngCarrot = new javax.swing.JLabel();
        pngOrange = new javax.swing.JLabel();
        pngMango = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(null);
        setPreferredSize(new java.awt.Dimension(649, 478));
        setSize(new java.awt.Dimension(649, 478));
        setLayout(null);

        sVGSalesGraph.setForeground(new java.awt.Color(0, 0, 0));
        sVGSalesGraph.setText("sVGSalesGraph");
        add(sVGSalesGraph);
        sVGSalesGraph.setBounds(25, 20, 292, 183);

        sVGYieldGraph.setForeground(new java.awt.Color(0, 0, 0));
        sVGYieldGraph.setText("sVGYieldGraph");
        add(sVGYieldGraph);
        sVGYieldGraph.setBounds(337, 20, 292, 183);

        pngTomato.setForeground(new java.awt.Color(0, 0, 0));
        pngTomato.setText("pngTomato");
        add(pngTomato);
        pngTomato.setBounds(25, 223, 188, 112);

        pngCorn.setForeground(new java.awt.Color(0, 0, 0));
        pngCorn.setText("pngCorn");
        pngCorn.setToolTipText("");
        add(pngCorn);
        pngCorn.setBounds(233, 223, 188, 112);

        pngApple.setForeground(new java.awt.Color(0, 0, 0));
        pngApple.setText("pngApple");
        add(pngApple);
        pngApple.setBounds(441, 223, 188, 112);

        lblTomato.setFont(new java.awt.Font("SF Pro Text", 1, 15)); // NOI18N
        lblTomato.setForeground(new java.awt.Color(0, 0, 0));
        lblTomato.setText("Tomato");
        add(lblTomato);
        lblTomato.setBounds(25, 343, 60, 20);

        lblTomatoAcre.setFont(new java.awt.Font("SF Pro Text", 0, 11)); // NOI18N
        lblTomatoAcre.setForeground(new java.awt.Color(0, 0, 0));
        lblTomatoAcre.setText("1.5 acre");
        add(lblTomatoAcre);
        lblTomatoAcre.setBounds(25, 363, 42, 20);

        lblCorn.setFont(new java.awt.Font("SF Pro Text", 1, 15)); // NOI18N
        lblCorn.setForeground(new java.awt.Color(0, 0, 0));
        lblCorn.setText("Corn");
        add(lblCorn);
        lblCorn.setBounds(233, 343, 60, 20);

        lblCornAcre.setFont(new java.awt.Font("SF Pro Text", 0, 11)); // NOI18N
        lblCornAcre.setForeground(new java.awt.Color(0, 0, 0));
        lblCornAcre.setText("2 acre");
        add(lblCornAcre);
        lblCornAcre.setBounds(233, 363, 42, 20);

        lblAppleAcre.setFont(new java.awt.Font("SF Pro Text", 0, 11)); // NOI18N
        lblAppleAcre.setForeground(new java.awt.Color(0, 0, 0));
        lblAppleAcre.setText("2.5 acre");
        add(lblAppleAcre);
        lblAppleAcre.setBounds(441, 363, 42, 20);

        lblApple.setFont(new java.awt.Font("SF Pro Text", 1, 15)); // NOI18N
        lblApple.setForeground(new java.awt.Color(0, 0, 0));
        lblApple.setText("Apple");
        add(lblApple);
        lblApple.setBounds(441, 343, 60, 20);

        lblCarrotAcre.setFont(new java.awt.Font("SF Pro Text", 0, 11)); // NOI18N
        lblCarrotAcre.setForeground(new java.awt.Color(0, 0, 0));
        lblCarrotAcre.setText("0.4 acre");
        add(lblCarrotAcre);
        lblCarrotAcre.setBounds(25, 537, 42, 20);

        lblCarrot.setFont(new java.awt.Font("SF Pro Text", 1, 15)); // NOI18N
        lblCarrot.setForeground(new java.awt.Color(0, 0, 0));
        lblCarrot.setText("Carrot");
        add(lblCarrot);
        lblCarrot.setBounds(25, 517, 60, 20);

        lblOrange.setFont(new java.awt.Font("SF Pro Text", 1, 15)); // NOI18N
        lblOrange.setForeground(new java.awt.Color(0, 0, 0));
        lblOrange.setText("Orange");
        add(lblOrange);
        lblOrange.setBounds(233, 517, 60, 20);

        lblOrangeAcre.setFont(new java.awt.Font("SF Pro Text", 0, 11)); // NOI18N
        lblOrangeAcre.setForeground(new java.awt.Color(0, 0, 0));
        lblOrangeAcre.setText("3.2 acre");
        add(lblOrangeAcre);
        lblOrangeAcre.setBounds(233, 537, 42, 20);

        lblMango.setFont(new java.awt.Font("SF Pro Text", 1, 15)); // NOI18N
        lblMango.setForeground(new java.awt.Color(0, 0, 0));
        lblMango.setText("Mango");
        add(lblMango);
        lblMango.setBounds(441, 517, 60, 20);

        lblMangoAcre.setFont(new java.awt.Font("SF Pro Text", 0, 11)); // NOI18N
        lblMangoAcre.setForeground(new java.awt.Color(0, 0, 0));
        lblMangoAcre.setText("2.3 acre");
        add(lblMangoAcre);
        lblMangoAcre.setBounds(441, 537, 42, 20);

        pngCarrot.setForeground(new java.awt.Color(0, 0, 0));
        pngCarrot.setText("pngCarrot");
        add(pngCarrot);
        pngCarrot.setBounds(25, 397, 188, 112);

        pngOrange.setForeground(new java.awt.Color(0, 0, 0));
        pngOrange.setText("pngOrange");
        add(pngOrange);
        pngOrange.setBounds(233, 397, 188, 112);

        pngMango.setForeground(new java.awt.Color(0, 0, 0));
        pngMango.setText("pngMango");
        add(pngMango);
        pngMango.setBounds(441, 397, 188, 112);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblApple;
    private javax.swing.JLabel lblAppleAcre;
    private javax.swing.JLabel lblCarrot;
    private javax.swing.JLabel lblCarrotAcre;
    private javax.swing.JLabel lblCorn;
    private javax.swing.JLabel lblCornAcre;
    private javax.swing.JLabel lblMango;
    private javax.swing.JLabel lblMangoAcre;
    private javax.swing.JLabel lblOrange;
    private javax.swing.JLabel lblOrangeAcre;
    private javax.swing.JLabel lblTomato;
    private javax.swing.JLabel lblTomatoAcre;
    private javax.swing.JLabel pngApple;
    private javax.swing.JLabel pngCarrot;
    private javax.swing.JLabel pngCorn;
    private javax.swing.JLabel pngMango;
    private javax.swing.JLabel pngOrange;
    private javax.swing.JLabel pngTomato;
    private main.SVGImage sVGSalesGraph;
    private main.SVGImage sVGYieldGraph;
    // End of variables declaration//GEN-END:variables
}
