/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package uis;

import java.awt.Cursor;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.sql.*;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author gamitha
 */
public class Login extends javax.swing.JPanel {

    /**
     * Creates new form Login
     */
    
    // Document listener and focus listener for textboxes
    private void addDocumentListenerAndFocusListener(JTextField textField, JLabel label) {
        textField.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                label.setVisible(true);
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                if (textField.getText().trim().isEmpty()) {
                    label.setVisible(false);
                }
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                // This method is not used in this example
            }
        });

        textField.addFocusListener(new FocusAdapter() {
            @Override
            public void focusLost(FocusEvent e) {
                if (textField.getText().trim().isEmpty()) {
                    textField.setVisible(false);
                }
            }
        });
    }
    
    public Login() {
        initComponents();
        
        // Set visibility off
        txtEmpID.setVisible(false);
        txtPassword.setVisible(false);
        sVGEmpIDClear.setVisible(false);
        sVGPasswordClear.setVisible(false);
        
        // Add document listeners
        addDocumentListenerAndFocusListener(txtEmpID, sVGEmpIDClear);
        addDocumentListenerAndFocusListener(txtPassword, sVGPasswordClear);
        
        // Set SVGs
        sVGNameLogo.setSvgImage("./svgcomponents/NameLogo.svg", 160, 32);
        sVGEmpIDTextBox.setSvgImage("./svgcomponents/EmpIDTextBox.svg", 206, 22);
        sVGPasswordTextBox.setSvgImage("./svgcomponents/PasswordTextBox.svg", 206, 22);
        sVGLoginBtn.setSvgImage("./svgcomponents/LoginBtn.svg", 52, 22);
        sVGEmpIDClear.setSvgImage("./svgcomponents/ClearBtn.svg", 16, 16);
        sVGPasswordClear.setSvgImage("./svgcomponents/ClearBtn.svg", 16, 16);
        
        // Set PNGs
        addImageToLabel();
        
        // Set Cursors
        Cursor txtCur = new Cursor(Cursor.TEXT_CURSOR);
        Cursor hand = new Cursor(Cursor.HAND_CURSOR);
        sVGEmpIDTextBox.setCursor(txtCur);
        sVGPasswordTextBox.setCursor(txtCur);
        sVGLoginBtn.setCursor(hand);
        lblForgotPass.setCursor(hand);
    }
    
    private void addImageToLabel() {
        // Toolbar Logo
        try {
            // Get the image
            java.net.URL imgURL = getClass().getResource("/pngcomponents/Logo.png");
            ImageIcon icon = new ImageIcon(imgURL);

            // Scale the image
            Image image = icon.getImage();
            Image newimg = image.getScaledInstance(150, 145, java.awt.Image.SCALE_SMOOTH); // Scale it the smooth way 
            icon = new ImageIcon(newimg);  // Transform it back

            // Add the image to the label
            pngLogo.setIcon(icon);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sVGPasswordClear = new main.SVGImage();
        sVGEmpIDClear = new main.SVGImage();
        txtEmpID = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        pngLogo = new javax.swing.JLabel();
        sVGNameLogo = new main.SVGImage();
        sVGPasswordTextBox = new main.SVGImage();
        sVGEmpIDTextBox = new main.SVGImage();
        sVGLoginBtn = new main.SVGImage();
        lblForgotPass = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(null);
        setSize(new java.awt.Dimension(850, 530));
        setLayout(null);

        sVGPasswordClear.setForeground(new java.awt.Color(0, 0, 0));
        sVGPasswordClear.setText("sVGPasswordClear");
        sVGPasswordClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sVGPasswordClearMouseClicked(evt);
            }
        });
        add(sVGPasswordClear);
        sVGPasswordClear.setBounds(507, 356, 16, 16);

        sVGEmpIDClear.setForeground(new java.awt.Color(0, 0, 0));
        sVGEmpIDClear.setText("sVGEmpIDClear");
        sVGEmpIDClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sVGEmpIDClearMouseClicked(evt);
            }
        });
        add(sVGEmpIDClear);
        sVGEmpIDClear.setBounds(507, 314, 16, 16);

        txtEmpID.setBackground(null);
        txtEmpID.setFont(new java.awt.Font("SF Pro Text", 0, 13)); // NOI18N
        txtEmpID.setForeground(new java.awt.Color(0, 0, 0));
        txtEmpID.setBorder(null);
        txtEmpID.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtEmpIDPropertyChange(evt);
            }
        });
        add(txtEmpID);
        txtEmpID.setBounds(329, 314, 192, 16);

        txtPassword.setBackground(null);
        txtPassword.setFont(new java.awt.Font("SF Pro Display", 0, 13)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(0, 0, 0));
        txtPassword.setBorder(null);
        add(txtPassword);
        txtPassword.setBounds(329, 356, 192, 16);

        pngLogo.setBackground(new java.awt.Color(0, 0, 0));
        pngLogo.setForeground(new java.awt.Color(0, 0, 0));
        pngLogo.setText("pngLogo");
        add(pngLogo);
        pngLogo.setBounds(350, 75, 150, 145);

        sVGNameLogo.setForeground(new java.awt.Color(0, 0, 0));
        sVGNameLogo.setText("sVGNameLogo");
        add(sVGNameLogo);
        sVGNameLogo.setBounds(345, 236, 160, 32);

        sVGPasswordTextBox.setForeground(new java.awt.Color(0, 0, 0));
        sVGPasswordTextBox.setText("sVGPasswordTextBox");
        sVGPasswordTextBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sVGPasswordTextBoxMouseClicked(evt);
            }
        });
        add(sVGPasswordTextBox);
        sVGPasswordTextBox.setBounds(322, 353, 206, 22);

        sVGEmpIDTextBox.setForeground(new java.awt.Color(0, 0, 0));
        sVGEmpIDTextBox.setText("sVGEmpIDTextBox");
        sVGEmpIDTextBox.setFocusable(false);
        sVGEmpIDTextBox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                sVGEmpIDTextBoxFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                sVGEmpIDTextBoxFocusLost(evt);
            }
        });
        sVGEmpIDTextBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sVGEmpIDTextBoxMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                sVGEmpIDTextBoxMouseReleased(evt);
            }
        });
        add(sVGEmpIDTextBox);
        sVGEmpIDTextBox.setBounds(322, 311, 206, 22);

        sVGLoginBtn.setForeground(new java.awt.Color(0, 0, 0));
        sVGLoginBtn.setText("sVGLoginBtn");
        sVGLoginBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sVGLoginBtnMouseClicked(evt);
            }
        });
        add(sVGLoginBtn);
        sVGLoginBtn.setBounds(477, 390, 52, 22);

        lblForgotPass.setFont(new java.awt.Font("SF Pro Text", 0, 11)); // NOI18N
        lblForgotPass.setForeground(new java.awt.Color(0, 0, 0));
        lblForgotPass.setText("<html><u>Forgot Password?</u></html>");
        add(lblForgotPass);
        lblForgotPass.setBounds(320, 398, 100, 14);
    }// </editor-fold>//GEN-END:initComponents

    private void sVGEmpIDTextBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sVGEmpIDTextBoxMouseClicked
        txtEmpID.setVisible(true);
        txtEmpID.requestFocusInWindow();
    }//GEN-LAST:event_sVGEmpIDTextBoxMouseClicked

    private void sVGEmpIDTextBoxFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_sVGEmpIDTextBoxFocusGained
        
    }//GEN-LAST:event_sVGEmpIDTextBoxFocusGained

    private void sVGEmpIDTextBoxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_sVGEmpIDTextBoxFocusLost
        
    }//GEN-LAST:event_sVGEmpIDTextBoxFocusLost

    private void sVGEmpIDTextBoxMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sVGEmpIDTextBoxMouseReleased
        
    }//GEN-LAST:event_sVGEmpIDTextBoxMouseReleased

    private void sVGPasswordTextBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sVGPasswordTextBoxMouseClicked
        txtPassword.setVisible(true);
        txtPassword.requestFocusInWindow();
    }//GEN-LAST:event_sVGPasswordTextBoxMouseClicked

    private void txtEmpIDPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtEmpIDPropertyChange
       
    }//GEN-LAST:event_txtEmpIDPropertyChange

    private void sVGEmpIDClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sVGEmpIDClearMouseClicked
        txtEmpID.setText("");
        sVGEmpIDClear.setVisible(false);
    }//GEN-LAST:event_sVGEmpIDClearMouseClicked

    private void sVGPasswordClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sVGPasswordClearMouseClicked
        txtPassword.setText("");
        sVGPasswordClear.setVisible(false);
    }//GEN-LAST:event_sVGPasswordClearMouseClicked

    private void sVGLoginBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sVGLoginBtnMouseClicked
        // Validating Employee ID and set it to a variable
        String stringEID = txtEmpID.getText();
        int eID = 0;
        if (stringEID.matches("\\d{4}")) {
            eID = Integer.parseInt(stringEID);
        } else {
            JOptionPane.showMessageDialog(null, "Invalid Employee ID");
            return;
        }
     
        // Set password into a variable
        String pass = txtPassword.getText();
        
        // Validate with the database
        Connection conn = null;
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/LittleGroot", "root" , "toor");
            
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM Employee WHERE EmpID = '" + eID + "' AND Pass = '" + pass + "'");
            
            if (rs.next()) {
                // Create user objects
                Main.createUserObj(eID, rs.getString("Fname"), rs.getString("LName"), rs.getString("EmpRole"), pass);
                
                // Displays Message and continue
                JOptionPane.showMessageDialog(null, "Successfully logged in!");
                this.setVisible(false);
                
                // Open Main
                Main mainFrame = new Main();
                mainFrame.setVisible(true);
                
                // Close self
                
            } else {
                // Display Error Message
                JOptionPane.showMessageDialog(null, "Invalid login");
            }
            
        } catch (ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(null, "Database Connection Error");
        } finally {
            if (conn != null) {
                try {
                    conn.close();
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(null, "Failed to close connection");
                }
            }
        }
    }//GEN-LAST:event_sVGLoginBtnMouseClicked


    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblForgotPass;
    private javax.swing.JLabel pngLogo;
    private main.SVGImage sVGEmpIDClear;
    private main.SVGImage sVGEmpIDTextBox;
    private main.SVGImage sVGLoginBtn;
    private main.SVGImage sVGNameLogo;
    private main.SVGImage sVGPasswordClear;
    private main.SVGImage sVGPasswordTextBox;
    private javax.swing.JTextField txtEmpID;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
