/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package uis;

/**
 *
 * @author gamitha
 */
public class Settings extends javax.swing.JPanel {

    /**
     * Creates new form Settings
     */
    public Settings() {
        initComponents();
        sVGAccountForm.setSvgImage("./svgcomponents/AccountForm.svg", 451, 52);
        sVGInfo1.setSvgImage("./svgcomponents/Info.svg", 16, 16);
        sVGInfo2.setSvgImage("./svgcomponents/Info.svg", 16, 16);
        sVGLogoutBtn.setSvgImage("./svgcomponents/LogoutBtn.svg", 57, 22);
        sVGChangePasswordForm.setSvgImage("./svgcomponents/ChangePasswordForm.svg", 451, 111);
        sVGOldPasswordTextBox.setSvgImage("./svgcomponents/OldPasswordTextBox.svg", 159, 23);
        sVGNewPasswordTextBox.setSvgImage("./svgcomponents/NewPasswordTextBox.svg", 159, 23);
        sVGVerifyPasswordsTextBox.setSvgImage("./svgcomponents/VerifyPasswordTextBox.svg", 159, 23);
        sVGChangePasswordBtn.setSvgImage("./svgcomponents/ChangePasswordBtn.svg", 124, 22);
        sVGAboutForm.setSvgImage("./svgcomponents/AboutForm.svg", 451, 52);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pngProfilePic = new javax.swing.JLabel();
        lblUserName = new javax.swing.JLabel();
        lblUserRole = new javax.swing.JLabel();
        lblAbout = new javax.swing.JLabel();
        sVGInfo2 = new main.SVGImage();
        sVGInfo1 = new main.SVGImage();
        sVGAccountForm = new main.SVGImage();
        sVGLogoutBtn = new main.SVGImage();
        sVGChangePasswordBtn = new main.SVGImage();
        lblAccount = new javax.swing.JLabel();
        sVGAboutForm = new main.SVGImage();
        sVGOldPasswordTextBox = new main.SVGImage();
        sVGNewPasswordTextBox = new main.SVGImage();
        sVGVerifyPasswordsTextBox = new main.SVGImage();
        sVGChangePasswordForm = new main.SVGImage();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(null);
        setSize(new java.awt.Dimension(649, 478));
        setLayout(null);

        pngProfilePic.setForeground(new java.awt.Color(0, 0, 0));
        pngProfilePic.setText("Profile Pic");
        add(pngProfilePic);
        pngProfilePic.setBounds(30, 55, 35, 35);

        lblUserName.setFont(new java.awt.Font("SF Pro Display", 0, 13)); // NOI18N
        lblUserName.setForeground(new java.awt.Color(0, 0, 0));
        lblUserName.setText("Name");
        add(lblUserName);
        lblUserName.setBounds(73, 56, 33, 20);

        lblUserRole.setFont(new java.awt.Font("SF Pro Display", 0, 11)); // NOI18N
        lblUserRole.setForeground(new java.awt.Color(0, 0, 0));
        lblUserRole.setText("Role");
        add(lblUserRole);
        lblUserRole.setBounds(73, 74, 70, 14);

        lblAbout.setFont(new java.awt.Font("SF Pro Text", 1, 13)); // NOI18N
        lblAbout.setForeground(new java.awt.Color(0, 0, 0));
        lblAbout.setText("About");
        add(lblAbout);
        lblAbout.setBounds(20, 342, 40, 16);

        sVGInfo2.setForeground(new java.awt.Color(0, 0, 0));
        sVGInfo2.setText("sVGInfo2");
        add(sVGInfo2);
        sVGInfo2.setBounds(445, 386, 16, 16);

        sVGInfo1.setForeground(new java.awt.Color(0, 0, 0));
        sVGInfo1.setText("sVGInfo1");
        add(sVGInfo1);
        sVGInfo1.setBounds(445, 64, 16, 16);

        sVGAccountForm.setForeground(new java.awt.Color(0, 0, 0));
        sVGAccountForm.setText("sVGAccountForm");
        add(sVGAccountForm);
        sVGAccountForm.setBounds(20, 46, 451, 52);

        sVGLogoutBtn.setForeground(new java.awt.Color(0, 0, 0));
        sVGLogoutBtn.setText("sVGLogoutBtn");
        add(sVGLogoutBtn);
        sVGLogoutBtn.setBounds(414, 113, 57, 22);

        sVGChangePasswordBtn.setForeground(new java.awt.Color(0, 0, 0));
        sVGChangePasswordBtn.setText("sVGChangePasswordBtn");
        add(sVGChangePasswordBtn);
        sVGChangePasswordBtn.setBounds(347, 290, 124, 22);

        lblAccount.setFont(new java.awt.Font("SF Pro Text", 1, 13)); // NOI18N
        lblAccount.setForeground(new java.awt.Color(0, 0, 0));
        lblAccount.setText("Account");
        add(lblAccount);
        lblAccount.setBounds(20, 20, 60, 16);

        sVGAboutForm.setForeground(new java.awt.Color(0, 0, 0));
        sVGAboutForm.setText("sVGAboutForm");
        add(sVGAboutForm);
        sVGAboutForm.setBounds(20, 368, 451, 52);

        sVGOldPasswordTextBox.setForeground(new java.awt.Color(0, 0, 0));
        sVGOldPasswordTextBox.setText("sVGOldPasswordTextBox");
        add(sVGOldPasswordTextBox);
        sVGOldPasswordTextBox.setBounds(302, 171, 159, 23);

        sVGNewPasswordTextBox.setForeground(new java.awt.Color(0, 0, 0));
        sVGNewPasswordTextBox.setText("sVGNewPasswordTextBox");
        add(sVGNewPasswordTextBox);
        sVGNewPasswordTextBox.setBounds(302, 208, 159, 23);

        sVGVerifyPasswordsTextBox.setForeground(new java.awt.Color(0, 0, 0));
        sVGVerifyPasswordsTextBox.setText("sVGVerifyPasswordsTextBox");
        add(sVGVerifyPasswordsTextBox);
        sVGVerifyPasswordsTextBox.setBounds(302, 245, 159, 23);

        sVGChangePasswordForm.setForeground(new java.awt.Color(0, 0, 0));
        sVGChangePasswordForm.setText("sVGChangePasswordForm");
        add(sVGChangePasswordForm);
        sVGChangePasswordForm.setBounds(20, 164, 451, 111);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblAbout;
    private javax.swing.JLabel lblAccount;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JLabel lblUserRole;
    private javax.swing.JLabel pngProfilePic;
    private main.SVGImage sVGAboutForm;
    private main.SVGImage sVGAccountForm;
    private main.SVGImage sVGChangePasswordBtn;
    private main.SVGImage sVGChangePasswordForm;
    private main.SVGImage sVGInfo1;
    private main.SVGImage sVGInfo2;
    private main.SVGImage sVGLogoutBtn;
    private main.SVGImage sVGNewPasswordTextBox;
    private main.SVGImage sVGOldPasswordTextBox;
    private main.SVGImage sVGVerifyPasswordsTextBox;
    // End of variables declaration//GEN-END:variables
}
